In [3]:
import numpy as np

# Question.1(Create a null vector of size 10 but the fifth value which is 1.)

In [39]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Question.2(Create a vector with values ranging from 10 to 49.)

In [11]:
v = np.arange(10,49)
print("Original vector:")
print(v)


Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Question.3(Create a 3x3 matrix with values ranging from 0 to 8)

In [15]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Questio.4(Find indices of non-zero elements from [1,2,0,0,4,0])

In [16]:
x = np.array([1,2,0,0,4,0])
x.nonzero()

(array([0, 1, 4], dtype=int64),)

# Question.5(Create a 10x10 array with random values and find the minimum and maximum values.)

In [17]:
x = np.random.randint(100,size=(10,10))
print(x)

[[99 46 50 48  0 92 10  7 68 81]
 [36 21 74 50 40 43 97 44 77 51]
 [79 54 31 28 97 37 93  6 95 66]
 [58 49 15 88 68 93  7 40 13 34]
 [61 31 19 87 95 37 55 71 69  2]
 [10 93 52 38  7 55 65 93 85  5]
 [64 47 23 31  8 58 60  2 62 24]
 [ 7 87 20 78 28 94 18 67 79 35]
 [39 51 21  2  5 67 11 89 43 95]
 [53 12 59  1 67 49  0 38  4 79]]


In [18]:
x.min()

0

In [19]:
x.max()

99

# Question.6(Create a random vector of size 30 and find the mean value.)

In [36]:
x = np.random.randint( 15 , size =30)
print(x)


[ 6  3  5 13 10  2 12 14 13  5  6 10  0  6 13 14 10  2  5  2  8  2  5 11
 12 10  4  7 11  8]


In [38]:
x.mean()

7.633333333333334